version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  postgres-e2e:
    container_name: postgres-e2e
    image: postgres:13
    environment:
      - POSTGRES_DB=db_e2e
      - POSTGRES_USER=e2e
      - POSTGRES_PASSWORD=e2e123
    ports:
      - 5433:5432
