name: API CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest
    container:
      image: node:16

    services:
      postgres-e2e:
        image: postgres:13
        env:
          POSTGRES_DB: db_e2e
          POSTGRES_USER: e2e
          POSTGRES_PASSWORD: e2e123
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run tests E2E
        run: npm run e2e:ci
        env:
          PORT: 3000
          DATABASE_URL: postgres://e2e:e2e123@postgres-e2e:5432/db_e2e
          API_KEY: 79823S
          JWT_SECRET: JWTSECRETAKAMARU
          SMTP_EMAIL: test@email.com
          SMTP_PASSWORD: password-email
